### ISSUE TITLE
Initial guess (Automatic) in Docker

### ISSUE THREAD

**Issue by Prabuddhi-05** [koide3/direct_visual_lidar_calibration#83]
In the Docker image of your repository in ROS2, could you please inform me about how "Initial guess Automatic" (initial_guess_auto) works? I'm encountering an error when testing it.
![Screenshot from 2024-05-16 16-03-22](https://github.com/koide3/direct_visual_lidar_calibration/assets/119497903/860014c8-812e-46a5-8bee-92c30d681564)

**Comment by Seekerzero** [comment]
Seems like the torch package was not sucessfully deployed into the container after pulling the image. Can you remove the original docker container and repull the image to see if there is any error about torch installation? Thanks.

**Comment by Prabuddhi-05** [comment]
As per your request, I removed the original Docker container and repulled the image. Unfortunately, the torch package still seems to be missing or not installed correctly. I am still getting the same error.

**Comment by Seekerzero** [comment]
could you try to post the installation log to here?

**Comment by Davabbb** [comment]
@Seekerzero i have same error

**Comment by Seekerzero** [comment]
Hi @koide3, seems like the GTSAM docker files does not setup the python environment properly. 
maybe add the following
`# Install PyTorch and torchvision
RUN pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html`shell
at [here](https://github.com/koide3/direct_visual_lidar_calibration/blob/8a03c738573b2ec0148d8ee39709ac3948ed7608/docker/noetic/Dockerfile#L28) (also the humble one) can ensure the installation.

Thanks.

**Comment by Davabbb** [comment]
@Seekerzero I created a docker based on yours and there are still not enough modules there

**Comment by Davabbb** [comment]
and there is an old docker file on github, here is an updated version, but it still doesn’t work for me https://hub.docker.com/r/koide3/direct_visual_lidar_calibration

**Comment by Seekerzero** [comment]
Thanks for your information. Do you have any errors report while you installing torch in docker?

**Comment by Davabbb** [comment]
@Seekerzero thanks for your quick response
my dockerfile:
`FROM koide3/direct_visual_lidar_calibration:humble

RUN apt-get update && apt-get install -y python3-pip

RUN pip3 install numpy==1.21.0
RUN pip3 install torch
RUN pip3 install opencv-python
RUN pip3 install matplotlib
RUN pip3 install torchvision
RUN pip3 install models`
I installed the modules that were needed step by step, but on the 8 layer i have error:
 > [8/8] RUN pip3 install models:                                                                                      
0.929 Collecting models                                                                                                
1.131   Downloading models-0.9.3.tar.gz (16 kB)                                                                        
1.189   Preparing metadata (setup.py): started
1.354   Preparing metadata (setup.py): finished with status 'error'
1.362   error: subprocess-exited-with-error
1.362   
1.362   × python setup.py egg_info did not run successfully.
1.362   │ exit code: 1
1.362   ╰─> [8 lines of output]
1.362       Traceback (most recent call last):
1.362         File "<string>", line 2, in <module>
1.362         File "<pip-setuptools-caller>", line 34, in <module>
1.362         File "/tmp/pip-install-9_hqdy_l/models_7c2cba2a7c3b46c897307929c70d7580/setup.py", line 25, in <module>
1.362           import models
1.362         File "/tmp/pip-install-9_hqdy_l/models_7c2cba2a7c3b46c897307929c70d7580/models/__init__.py", line 23, in <module>
1.362           from base import *
1.362       ModuleNotFoundError: No module named 'base'
1.362       [end of output]
1.362   
1.362   note: This error originates from a subprocess, and is likely not a problem with pip.
1.364 error: metadata-generation-failed

**Comment by Davabbb** [comment]
if i try install base 
5.247 ERROR: Could not find a version that satisfies the requirement base (from versions: 0.0.0)
5.247 ERROR: No matching distribution found for base

**Comment by Seekerzero** [comment]
This might be related to the version of pip3 and setuptools try to upgrade them first.

**Comment by Davabbb** [comment]
i solve problem with models, clone this repo https://github.com/magicleap/SuperGluePretrainedNetwork/tree/master and copy models folder

**Comment by Davabbb** [comment]
Traceback (most recent call last):
  File "/root/ros2_ws/install/direct_visual_lidar_calibration/lib/direct_visual_lidar_calibration/find_matches_superglue.py", line 157, in <module>
    main()
  File "/root/ros2_ws/install/direct_visual_lidar_calibration/lib/direct_visual_lidar_calibration/find_matches_superglue.py", line 136, in main
    cmap = matplotlib.cm.get_cmap('turbo')
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
[ros2run]: Process exited with failure 1
:)

**Comment by Seekerzero** [comment]
this is the version problem with matplotlib, either you can downgrade it (might cause problem with numpy) or you just edit the code to adapt the newer version.

**Comment by Davabbb** [comment]
try install matplotlib 3.4.0

**Comment by Davabbb** [comment]
FROM koide3/direct_visual_lidar_calibration:humble

RUN apt-get update && apt-get install -y python3-pip

RUN pip3 install numpy==1.21.0
RUN pip3 install torch
RUN pip3 install opencv-python
RUN pip3 install torchvision
RUN pip3 install matplotlib==3.7.3

COPY ./models /root/ros2_ws/src/direct_visual_lidar_calibration/scripts/models
COPY ./models /root/ros2_ws/install/direct_visual_lidar_calibration/lib/direct_visual_lidar_calibration/models

git clone https://github.com/magicleap/SuperGluePretrainedNetwork/tree/master

its work!!

**Comment by Seekerzero** [comment]
Hi @koide3, you might want to add the lines above to the dockerfile for setting up the torch environment.

**Comment by Davabbb** [comment]
@Seekerzero can you please help me with another error?

**Comment by Seekerzero** [comment]
hi @Davabbb,  you might want to raise another issue if the question is not related to this one.

**Comment by koide3** [comment]
Hi guys,
If I remember correctly, I avoided including SuperGlue in the docker image because of its license. MagicLeap employs a non-standard strict license, and I was not sure if it's safe to include it. I have read the license again, and I'm still not sure if it allows redistributing the code in a binary docker image. Does anybody have idea about this?

I think it is safe to provide a separate Dockerfile with SuperGlue at least, and I'm going to add something like `Dockerfile_with_superglue`.

@Seekerzero Thank a lot for your help!, and sorry for making you respond to issues.

**Comment by koide3** [comment]
I just added `Dockerfile_with_superglue`.
https://github.com/koide3/direct_visual_lidar_calibration/blob/main/docker/humble/Dockerfile_with_superglue

**Comment by Seekerzero** [comment]
> Hi guys,
> If I remember correctly, I avoided including SuperGlue in the docker image because of its license. MagicLeap employs a non-standard strict license, and I was not sure if it's safe to include it. I have read the license again, but I'm still not sure if it allows redistributing the code in a binary docker image. Does anybody have idea about this?
> 
> I think it is safe to provide a separate Dockerfile with SuperGlue at least, and I'm going to add something like `Dockerfile_with_superglue` so that the user can build the image by themselves.
> 
> @Seekerzero Thank a lot for your help!, and sorry for making you respond to issues.

Hi @koide3, you are right, seems like magic leap prohibited any kinds of sublicense from its original copy, even for the research purpose. We want to avoid this risk from it, also the risk of docker distribution. Sorry for not realizing that! 
We might want to add a way let user link the external path from the superglue folder to the docker file. Or in the future, we can introduce more framework for auto matching.

It is my pleasure to help!
